import type { Escalation, MerchantStats, DashboardStats } from "@/types";

export const mockEscalations: Escalation[] = [
  {
    id: "esc-001",
    source: "gmail",
    subject: "Payment gateway failure - urgent",
    merchantName: "FashionHub",
    merchantId: "MID-1234",
    status: "sla_breached",
    priority: "critical",
    assignee: "Shreyaskar Singh",
    assigneeEmail: "shreyaskar.singh@gokwik.co",
    createdAt: new Date(Date.now() - 10 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 9 * 3600000).toISOString(),
    lastMessageAt: new Date(Date.now() - 9 * 3600000).toISOString(),
    threadId: "thread-001",
    messageCount: 5,
    snippet: "Hi, our checkout is throwing 502 errors since 9am. We've lost ~50 orders already. This is critical...",
    waitingSince: new Date(Date.now() - 9 * 3600000).toISOString(),
    category: "Payment",
    tags: ["gateway", "urgent", "downtime"],
    isRead: false,
  },
  {
    id: "esc-002",
    source: "slack",
    subject: "RTO rate spike this week",
    merchantName: "StyleCraft",
    merchantId: "MID-5678",
    status: "open",
    priority: "high",
    assignee: "Priya Sharma",
    assigneeEmail: "priya.sharma@gokwik.co",
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    lastMessageAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    channelId: "C01ABC",
    messageCount: 12,
    snippet: "Hey team, our RTO has jumped from 12% to 23% this week. Can someone check the COD intelligence config?",
    waitingSince: new Date(Date.now() - 2 * 3600000).toISOString(),
    category: "RTO",
    tags: ["rto", "cod-intelligence"],
    isRead: true,
  },
  {
    id: "esc-003",
    source: "jira",
    subject: "[GKW-4521] Shopify plugin not loading on mobile",
    merchantName: "TrendStore",
    merchantId: "MID-9012",
    status: "pending_reply",
    priority: "medium",
    assignee: "Rahul Verma",
    assigneeEmail: "rahul.verma@gokwik.co",
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    lastMessageAt: new Date(Date.now() - 3600000).toISOString(),
    jiraKey: "GKW-4521",
    messageCount: 8,
    snippet: "Plugin fails to render on iOS Safari. Reproducible on iPhone 13 and 14. Merchant reports 30% drop in mobile conversions.",
    category: "Integration",
    tags: ["shopify", "mobile", "ios"],
    isRead: true,
  },
  {
    id: "esc-004",
    source: "gmail",
    subject: "Need help with KYC document upload",
    merchantName: "QuickBuy",
    merchantId: "MID-3456",
    status: "open",
    priority: "low",
    assignee: "Shreyaskar Singh",
    assigneeEmail: "shreyaskar.singh@gokwik.co",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    lastMessageAt: new Date(Date.now() - 30 * 60000).toISOString(),
    threadId: "thread-004",
    messageCount: 3,
    snippet: "Hello, I'm trying to upload my GST certificate but the portal keeps saying invalid format. I've tried PDF and JPG...",
    category: "KYC",
    tags: ["kyc", "onboarding"],
    isRead: false,
  },
  {
    id: "esc-005",
    source: "slack",
    subject: "COD order confirmation SMS not going",
    merchantName: "HomeBazaar",
    merchantId: "MID-7890",
    status: "closed",
    priority: "high",
    assignee: "Priya Sharma",
    assigneeEmail: "priya.sharma@gokwik.co",
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    lastMessageAt: new Date(Date.now() - 86400000).toISOString(),
    channelId: "C01DEF",
    messageCount: 15,
    snippet: "RESOLVED: Was a misconfiguration in the SMS provider API key. Fixed and tested.",
    category: "SMS",
    tags: ["sms", "cod", "resolved"],
    isRead: true,
  },
  {
    id: "esc-006",
    source: "jira",
    subject: "[GKW-4498] Webhook events not being received",
    merchantName: "GadgetWorld",
    merchantId: "MID-2345",
    status: "pending_reply",
    priority: "high",
    assignee: "Rahul Verma",
    assigneeEmail: "rahul.verma@gokwik.co",
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    lastMessageAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    jiraKey: "GKW-4498",
    messageCount: 6,
    snippet: "Merchant's backend not receiving order.confirmed events. Endpoint returns 200 when tested manually.",
    waitingSince: new Date(Date.now() - 5 * 3600000).toISOString(),
    category: "Integration",
    tags: ["webhook", "api"],
    isRead: true,
  },
];

export const mockMerchantStats: MerchantStats[] = [
  {
    merchantId: "MID-1234",
    merchantName: "FashionHub",
    totalEscalations: 24,
    openEscalations: 3,
    avgResolutionHours: 18.5,
    slaBreaches: 4,
    healthScore: 32,
    trend: "degrading",
    categories: { Payment: 10, RTO: 6, Integration: 5, KYC: 3 },
  },
  {
    merchantId: "MID-5678",
    merchantName: "StyleCraft",
    totalEscalations: 11,
    openEscalations: 1,
    avgResolutionHours: 6.2,
    slaBreaches: 0,
    healthScore: 78,
    trend: "stable",
    categories: { RTO: 5, SMS: 3, Payment: 2, KYC: 1 },
  },
  {
    merchantId: "MID-9012",
    merchantName: "TrendStore",
    totalEscalations: 18,
    openEscalations: 2,
    avgResolutionHours: 12.1,
    slaBreaches: 2,
    healthScore: 55,
    trend: "improving",
    categories: { Integration: 8, Payment: 5, RTO: 3, SMS: 2 },
  },
  {
    merchantId: "MID-3456",
    merchantName: "QuickBuy",
    totalEscalations: 7,
    openEscalations: 1,
    avgResolutionHours: 4.8,
    slaBreaches: 0,
    healthScore: 82,
    trend: "stable",
    categories: { KYC: 4, Payment: 2, Integration: 1 },
  },
  {
    merchantId: "MID-7890",
    merchantName: "HomeBazaar",
    totalEscalations: 31,
    openEscalations: 0,
    avgResolutionHours: 8.3,
    slaBreaches: 1,
    healthScore: 67,
    trend: "improving",
    categories: { SMS: 12, COD: 10, Payment: 6, RTO: 3 },
  },
];

export const mockDashboardStats: DashboardStats = {
  totalOpen: 4,
  pendingReply: 2,
  closedToday: 3,
  slaBreached: 1,
  avgResponseTimeHours: 4.7,
  totalThisWeek: 18,
};

export const mockWeeklyData = [
  { day: "Mon", open: 8, closed: 5, breached: 1 },
  { day: "Tue", open: 12, closed: 9, breached: 2 },
  { day: "Wed", open: 7, closed: 11, breached: 0 },
  { day: "Thu", open: 15, closed: 8, breached: 3 },
  { day: "Fri", open: 10, closed: 13, breached: 1 },
  { day: "Sat", open: 4, closed: 6, breached: 0 },
  { day: "Sun", open: 2, closed: 3, breached: 0 },
];

export const mockCategoryData = [
  { name: "Payment", value: 28, color: "#001b44" },
  { name: "Integration", value: 22, color: "#006d43" },
  { name: "RTO", value: 18, color: "#fbbc00" },
  { name: "SMS/COD", value: 15, color: "#3c5d9c" },
  { name: "KYC", value: 12, color: "#ba1a1a" },
  { name: "Other", value: 5, color: "#747781" },
];
